name: sapp
description: Run sapp to convert static analysis results to SARIF format.

inputs:
  filters-directory:
    description: Path to the filters directory containing filters. Default is the filter's directory in pyre-check
    required: false
    default: '~/lib/pyre_check/pysa_filters'
  taint-output:
    description: Path to the taint-output file derived from the static analyzer. Default is ./taint-output.json
    default: './taint-output.json'
  version:
    description: Version of sapp to be used. Default is latest.
    default: 'latest'

runs:
  using: "composite"
  steps:
    - run: if [ ${{inputs.version}} = "latest" ]; then pip install fb-sapp; else pip install fb-sapp==${{inputs.version}}; fi
      shell: bash
    - run: sapp update warning-codes ./taint-metadata.json
      shell: bash
    - run: if [ ! -f ${{inputs.taint-output}} ]; then echo "No such file: "${{inputs.taint-output}}; exit 1; fi
      shell: bash
    - run: sapp analyze ${{inputs.taint-output}}
      shell: bash
    - run: sapp filter issues 1 ${{inputs.filters-directory}} --output-format sarif > sarif.json
      shell: bash
