name: sapp
description: Run sapp to convert static analysis results to SARIF format.

inputs:
  include-default-filters:
    # TODO
    description: include default filters with static analysis tool
    required: true
    type: boolean
  filters-directory:
    description: Path to the filters directory containing your custom SAPP filters
    required: false
  tool:
    type: choice
    # TODO
    description: static analysis tool
    required: true
    options:
      - pysa
      - mariana-trench
  artifact-handle:
    # TODO
    description: name of handle used to save static analysis results
    required: true
  version:
    description: Version of sapp to be used. Default is latest.
    default: 'latest'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{inputs.artifact-handle}}
        path: ./
      # TODO fill in
    - run: if [ ${{inputs.version}} = "latest" ]; then pip install fb-sapp; else pip install fb-sapp==${{inputs.version}}; fi
      shell: bash
    - run: sapp update warning-codes ./taint-metadata.json
      shell: bash
    - run: sapp analyze ./taint-output.json
      shell: bash
      # TODO allow custom filter directories to be submitted
    - run: sapp filter issues 1 ${{env.LD_LIBRARY_PATH}}/pyre_check/pysa_filters --output-format sarif > sarif.json
      shell: bash
    - name: Saving filtered results in SARIF
      uses: actions/upload-artifact@v2
      with:
        name: sarif-results
        path: sarif.json
        if-no-files-found: error
