name: sapp
description: Run sapp to convert static analysis results to SARIF format.

inputs:
  filters-directory:
    description: Path to the filters directory containing filters. Default is the filter's directory in pyre-check
    default: '~/lib/pyre_check/pysa_filters'
  # taint-output:
  #   description: Path to the taint-output file derived from the static analyzer. Default is ./taint-output.json
  #   default: './taint-output.json'
  # taint-metadata:
  #   description: Path to the taint-metadata file derived from the static analyzer. Default is ./taint-metadata.json
  #   default: './taint-metadata.json'
  artifact-handle:
    description: name of handle used to save static analysis results
  version:
    description: Version of sapp to be used. Default is latest.
    default: 'latest'
  # consider using working-directory isntead
  # https://github.com/actions/runner/issues/834
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{inputs.artifact-handle}}
        path: ./
    - run: ls -la
      shell: bash
    - run: pwd
      shell: bash
    - run: if [ ${{inputs.version}} = "latest" ]; then pip install fb-sapp; else pip install fb-sapp==${{inputs.version}}; fi
      shell: bash
    # - run: pip install fb-sapp
    #   shell: bash
    - run: sapp update warning-codes ${{inputs.artifact-handle}}/taint-metadata.json
      shell: bash
    - run: sapp analyze ${{inputs.artifact-handle}}/taint-output.json
      shell: bash
    - id: sarif-output
      run: sapp filter issues 1 ${{inputs.filters-directory}} --output-format sarif > sarif.json
      shell: bash


# https://stackoverflow.com/questions/66216251/publish-github-action-to-marketplace-unexpected-value-steps
# https://github.com/actions/runner/issues/1593
