name: sapp
description: Run sapp to convert static analysis results to SARIF format.

inputs:
  include-default-filters:
    # TODO
    description: include default filters with static analysis tool
    default: true
    type: boolean
  filters-directory:
    description: Path to the filters directory containing your custom SAPP filters
    required: false
  artifact-handle:
    # TODO
    description: name of handle used to save static analysis results
    required: true
  version:
    description: Version of sapp to be used. Default is latest.
    default: 'latest'
    required: false

runs:
  using: "composite"
  steps:
    - name: Retrieve static analysis results
      uses: actions/download-artifact@v2
      with:
        name: ${{inputs.artifact-handle}}
        path: ./

    - name: Install SAPP
      run: if [ ${{inputs.version}} = "latest" ]; then pip install fb-sapp; else pip install fb-sapp==${{inputs.version}}; fi
      shell: bash

    - name: Set up SAPP
      run: sapp update warning-codes ./taint-metadata.json
      shell: bash

    - name: Ingest Pysa results
      run: sapp analyze ./taint-output.json
      shell: bash

    - name: Set up to include default filters
      # https://github.com/actions/runner/issues/1483
      if: ${{inputs.include-default-filters == 'true'}}
      run: |
        echo ${{inputs.include-default-filters}}
        mkdir filters
        cp -r ${{env.LD_LIBRARY_PATH}}/pyre_check/pysa_filters filters
        ls -la filters
      shell: bash

    - name: Set up to include custom filters
      if: ${{inputs.filters-directory != ''}}
      run: |
        [ ! -d ${{inputs.filters-directory}} ] && exit 1
        mkdir -p filters
        cp -r ${{inputs.filters-directory}} filters
        ls -la filters
      shell: bash

    - name: Filter Pysa results
      if: ${{inputs.include-default-filters}} || ${{inputs.filters-directory != ''}}
      run: sapp filter issues 1 filters --output-format sarif > sarif.json
      shell: bash

    - name: Saving filtered results in SARIF
      uses: actions/upload-artifact@v2
      with:
        name: sarif-results
        path: sarif.json
        if-no-files-found: error
