name: Testing SAPP GitHub Action with Pysa

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out sapp-action repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up Pyre
        run: pip install pyre-check

      - name: Set up deliberately_vulnerable_flask_app
        run: |
          cd test/pyre-check/documentation/deliberately_vulnerable_flask_app
          . ./setup.sh

      - name: Run Pysa
        # TODO replace with Pysa action later
        run: |
          cd test/pyre-check/documentation/deliberately_vulnerable_flask_app
          pyre analyze --no-verify --save-results-to=./pysa-output
          ls -la

      - name: Saving Pysa results for SAPP
        uses: actions/upload-artifact@v2
        with:
          name: pysa-results
          # TODO replace with Pysa action later
          path: ./test/pyre-check/documentation/deliberately_vulnerable_flask_app/pysa-output
          if-no-files-found: error

      - name: Run SAPP
        uses: ./
        with:
          artifact-handle: pysa-results
          include-default-filters: true
          filters-directory: ./test/custom-filters

      - name: Retrieve Pysa results in SARIF
        uses: actions/download-artifact@v2
        with:
          name: sarif-results
          path: ./

      - name: Expose SARIF Results
        uses: actions/upload-artifact@v2
        with:
          name: SARIF Results
          path: sarif.json

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif.json
